### ISSUE TITLE
Why not print all compilers?

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/Artifact-description#1]

**Comment by TomTheBear** [comment]
Currently it tests only for ICC, GCC and CLANG but there would be more, especially when it comes to ARM and POWER. Since ICC is commonly the best on x86, it searches for this one first.

I'll update that

**Comment by TomTheBear** [comment]
Fixed in https://github.com/RRZE-HPC/Artifact-description/commit/a63e2c9f57f57e17f9c787a8392dd1f9ad5c03a2
